// Sunucu karne mantığı testi (node:sqlite ile D1 taklidi): ölçüm, takılan hisse, 21:00 son saat, Telegram reddinde yeniden deneme, hata defteri.
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const W = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'worker', 'src');
const db = new DatabaseSync(':memory:');
const mk = sql => { let a = []; const o = { bind: (...x) => { a = x; return o; }, first: async () => db.prepare(sql).get(...a) ?? null, all: async () => ({ results: db.prepare(sql).all(...a) }), run: async () => { const r = db.prepare(sql).run(...a); return { meta: { changes: r.changes } }; }, _run: () => db.prepare(sql).run(...a) }; return o; };
const env = { BT: { prepare: mk, batch: async L => { for (const x of L) x._run(); } } };
db.exec('CREATE TABLE meta (k TEXT PRIMARY KEY, v TEXT)');
const { sigEval } = await import(path.join(W, 'sig.js'));
const res = []; const ok = (n, c, i) => { res.push(!!c); console.log((c ? '✓ ' : '✗ ') + n + (i ? ' — ' + i : '')); };
let T0; const at = hm => { T0 = Date.parse('2026-10-01T' + hm + ':00+03:00'); Date.now = () => T0; };
let tgOk = true; const sent = [];
const tgSend = async (c, m) => { sent.push(m); return tgOk ? { ok: true } : { ok: false, error: 'Unauthorized' }; };
const kvGet = async () => ({ tgTok: 'x', chat: '1' }), esc = s => String(s), nf = x => x;
const meta = k => (db.prepare('SELECT v FROM meta WHERE k=?').get(k) || {}).v;
at('11:00'); await sigEval(env, async () => ({}), tgSend, kvGet, esc, nf);
const ins = (sym, hm, done) => db.prepare("INSERT INTO sig (src,d,t,sym,dir,px,done,o10) VALUES ('radar','2026-10-01',?,?,'AL',10,?,?)").run(Date.parse('2026-10-01T' + hm + ':00+03:00'), sym, done, done ? 1 : null);
ins('AAA', '11:00', 1); ins('BBB', '12:00', 0); ins('CCC', '12:05', 0);
const bar = t => [t / 1000, 10, 10.2, 9.95, 10.1, 100];
const fetchBarsTV = async (e, syms) => { const o = {}; for (const s of syms) { const m = new Map(); if (!s.includes('BBB')) for (let i = 0; i < 400; i++) { const t = Date.parse('2026-10-01T10:00:00+03:00') + i * 60e3; m.set(t, bar(t)); } o[s] = { m, err: '' }; } return o; };
at('18:30'); await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf);
for (let i = 0; i < 3; i++) await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf);
ok('CCC ölçüldü, BBB (verisiz) bekliyor', db.prepare("SELECT count(*) n FROM sig WHERE done=0").get().n === 1);
ok('21:00 öncesi eksikken rapor gitmedi', sent.length === 0);
ok('veri gelmeyen hisse toparlama olarak deftere yazıldı', db.prepare("SELECT count(*) n FROM err WHERE kind='toparlama'").get().n >= 1);
tgOk = false; at('21:01'); await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf);
ok('Telegram reddinde rapor gönderildi sayılmadı', sent.length === 1 && !meta('sigsum'));
ok('rapor hatası deftere yazıldı', db.prepare("SELECT count(*) n FROM err WHERE msg LIKE 'karne raporu gönderilemedi%'").get().n === 1);
at('21:05'); await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf); ok('10 dk dolmadan yeniden denemedi', sent.length === 1);
tgOk = true; at('21:12'); await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf); ok('10 dk sonra gönderildi', sent.length === 2 && meta('sigsum') === '2026-10-01');
at('21:20'); await sigEval(env, fetchBarsTV, tgSend, kvGet, esc, nf); ok('bir kez gönderildikten sonra tekrar yok', sent.length === 2);
ok('raporda veri gelmedi notu', /veri gelmedi/.test(sent[1]));
console.log('\nKARNE: ' + res.filter(Boolean).length + '/' + res.length + ' geçti');
process.exit(res.every(Boolean) ? 0 : 1);
